# -*- coding: utf-8 -*-
"""Foro#1-JimenaCampos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHkA5EDnTgm1cmwg4EF-I-Ep3agObyVf

# **Foro 1**
Ejercicio #1
"""

x = "Hello World!"
print(x)